name: Project sync

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened]

permissions: {}

jobs:
  sync:
    uses: ZirekHQ/.github/.github/workflows/project-sync.yml@7e29bd4f72bace4ca26745a83d0a33386c678bf5 # main
    secrets:
      PROJECT_APP_CLIENT_ID: ${{ secrets.PROJECT_APP_CLIENT_ID }}
      PROJECT_APP_PRIVATE_KEY: ${{ secrets.PROJECT_APP_PRIVATE_KEY }}
